Repository Qiskit/documentation, pull requests merged in 2023-12, with the labels that each got.

#366 Document Qiskit versioning and stability policy
  cSpell.json
  docs/start/install.mdx
  public/images/start/install/release_schedule.png
Labels: content 📄, section: start

#486 Fix `IterativeAmplitudeEstimation` pages crashing due to bad Latex
  docs/api/qiskit/0.25/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.26/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.27/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.28/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.29/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.30/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.31/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.32/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.33/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.34/qiskit.algorithms.IterativeAmplitudeEstimation.md
  docs/api/qiskit/0.35/qiskit.algorithms.IterativeAmplitudeEstimation.md
Labels: infra 🏗️

#497 Add missing images for 0.32 Qiskit docs
  public/images/api/qiskit/0.32/qiskit.circuit.QuantumCircuit.draw_0_0.png
  public/images/api/qiskit/0.32/qiskit.circuit.library.IQP_0_0.png
  public/images/api/qiskit/0.32/qiskit.circuit.library.Permutation_0_0.png
  public/images/api/qiskit/0.32/qiskit.circuit.library.PiecewiseChebyshev_0_0.png
  public/images/api/qiskit/0.32/qiskit.circuit.library.QuantumVolume_0_0.png
  public/images/api/qiskit/0.32/qiskit.circuit.random.random_circuit_0_0.png
  public/images/api/qiskit/0.32/qiskit.converters.ast_to_dag_0_0.png
  public/images/api/qiskit/0.32/qiskit.converters.circuit_to_dag_0_0.png
  public/images/api/qiskit/0.32/qiskit.ignis.mitigation.expval_meas_mitigator_circuits_0_1.png
  public/images/api/qiskit/0.32/qiskit.ml.circuit.library.RawFeatureVector.draw_0_0.png
  public/images/api/qiskit/0.32/qiskit.pulse.builder.align_equispaced_0_0.png
  public/images/api/qiskit/0.32/qiskit.pulse.builder.align_func_0_0.png
  public/images/api/qiskit/0.32/qiskit.transpiler.passes.DynamicalDecoupling_1_0.png
  public/images/api/qiskit/0.32/qiskit.transpiler.passes.DynamicalDecoupling_2_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.circuit_drawer_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.dag_drawer_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_bloch_multivector_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_bloch_vector_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_circuit_layout_1_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_error_map_1_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_gate_map_1_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_histogram_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_state_city_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_state_hinton_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_state_paulivec_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.plot_state_qsphere_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.pulse_v2.draw_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.pulse_v2.draw_1_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.pulse_v2.draw_2_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.timeline.draw_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.timeline.draw_1_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.timeline.draw_2_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.timeline_drawer_0_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.timeline_drawer_1_0.png
  public/images/api/qiskit/0.32/qiskit.visualization.timeline_drawer_2_0.png
Labels: infra 🏗️

#496 Speed up link checker by not loading historical API docs
  scripts/commands/checkLinks.ts
Labels: infra 🏗️

#292 Improve instructions for how to test out Dockerfile
  Dockerfile
Labels: infra 🏗️

#555 Rewrite `./start` script to Python
  start
Labels: infra 🏗️

#556 Refactor and test link checker's markdown handling
  scripts/commands/checkLinks.ts
  scripts/lib/links/LinkChecker.test.ts
  scripts/lib/links/LinkChecker.ts
  scripts/lib/links/ignores.ts
  scripts/lib/links/markdown.test.ts
  scripts/lib/links/markdown.ts
Labels: infra 🏗️

#557 Refactor link checker to use FileBatch class
  scripts/commands/checkLinks.ts
  scripts/lib/links/FileBatch.ts
  scripts/lib/links/LinkChecker.test.ts
  scripts/lib/links/LinkChecker.ts
Labels: infra 🏗️

#541 Add Crowdin to set up translations
  .github/workflows/crowdin-download-translations.yml
  .github/workflows/crowdin-upload-english.yml
  .github/workflows/staging.yml
  Dockerfile
  README.md
  crowdin.yml
  start
  translations/placeholder.txt
Labels: infra 🏗️, translations 🌍
