Repository Qiskit/documentation, pull requests merged in 2023-10, with the labels that each got.

#91 Migrate open source docs
  qiskit-docs/explanation/endianness.rst
  qiskit-docs/faq.rst
  qiskit-docs/how_to/use_sampler.rst
  qiskit-docs/migration_guides/algorithms_migration.rst
  qiskit-docs/migration_guides/opflow_migration.rst
  qiskit-docs/migration_guides/qi_migration.rst
  qiskit-docs/tutorials/circuits/01_circuit_basics.ipynb
  qiskit-docs/tutorials/circuits/1_getting_started_with_qiskit.ipynb
  qiskit-docs/tutorials/circuits/2_plotting_data_in_qiskit.ipynb
  qiskit-docs/tutorials/circuits_advanced/01_advanced_circuits.ipynb
  qiskit-docs/tutorials/circuits_advanced/02_operators_overview.ipynb
  qiskit-docs/tutorials/circuits_advanced/04_transpiler_passes_and_passmanager.ipynb
  qiskit-docs/tutorials/circuits_advanced/05_pulse_gates.ipynb
  qiskit-docs/tutorials/circuits_advanced/06_building_pulse_schedules.ipynb
  qiskit-docs/tutorials/circuits_advanced/07_pulse_scheduler.ipynb
  qiskit-docs/tutorials/circuits_advanced/08_gathering_system_information.ipynb
  runtime-docs/faqs/max_execution_time.rst
  runtime-docs/faqs/open_source_vs_ibm_cloud_primitives.rst
Labels: infra 🏗️

#119 Typo in hello world
  docs/start/hello-world.ipynb
Labels: content 📄, section: start, bug 🐛

#123 Remove runtime docs migrated from qiskit-ibm-runtime
  runtime-docs/faqs/max_execution_time.rst
  runtime-docs/faqs/open_source_vs_ibm_cloud_primitives.rst
Labels: infra 🏗️

#125 Properly attribute Git history for pulse tutorials
  docs/build/operators_overview.ipynb
  docs/build/pulse.ipynb
  qiskit-docs/tutorials/circuits_advanced/02_operators_overview.ipynb
  qiskit-docs/tutorials/circuits_advanced/05_pulse_gates.ipynb
  qiskit-docs/tutorials/circuits_advanced/06_building_pulse_schedules.ipynb
Labels: infra 🏗️

#132 Set up a staging site
  .github/workflows/preview-docs.yml
  .github/workflows/staging.yml
  README.md
Labels: infra 🏗️

#137 Move primitives material and Optimize to Run
  docs/build/_toc.json
  docs/build/index.mdx
  docs/optimize/_toc.json
  docs/optimize/index.mdx
  docs/run/_toc.json
  docs/run/algorithm-tuning-options.mdx
  docs/run/index.mdx
  docs/start/index.mdx
Labels: content 📄

#144 Fix broken links after toc reorganization
  docs/run/run-sessions.mdx
  docs/run/sessions.mdx
  docs/start/hello-world.ipynb
  docs/start/index.mdx
  docs/start/migrate-examples.mdx
  docs/start/migrate.mdx
  docs/start/runtime.mdx
  docs/test/noise.mdx
Labels: bug 🐛

#165 Convert Endianness how to from RST to MDX
  cSpell.json
  docs/build/__endianness.mdx
  docs/build/__endianness.rst
  docs/start/__migration-guide-algorithms.md
  docs/start/__migration-guide-opflow.md
  docs/start/__migration-guide-qi.md
  docs/verify/__use_estimator.md
  docs/verify/__use_estimator.rst
  docs/verify/__use_sampler.md
  docs/verify/__use_sampler.rst
  public/images/build/endianness/qft-normal.png
  public/images/build/endianness/qft-reversed.png
  scripts/commands/checkMetadata.ts
Labels: infra 🏗️

#170 Convert Estimator and Sampler how tos to MDX
  docs/build/__endianness.mdx
  docs/verify/__use_estimator.md
  docs/verify/__use_estimator.mdx
  docs/verify/__use_sampler.md
  docs/verify/__use_sampler.mdx
  public/images/verify/use_estimator/initialize.png
  public/images/verify/use_sampler/initialize.png
  scripts/commands/checkMetadata.ts
Labels: infra 🏗️

#168 Combine visualizations tutorials
  docs/build/__advanced_circuit_visualization.ipynb
  docs/build/_toc.json
  docs/build/circuit-visualization.ipynb
  docs/build/index.mdx
Labels: content 📄, section: build 🧱

#183 Remove what is qiskit section from the docs
  docs/start/_toc.json
  docs/start/intro-to-qiskit.ipynb
  docs/start/runtime.mdx
Labels: content 📄

#73 Update start page (based on Jay's edits)
  docs/run/index.mdx
  docs/start/index.mdx
Labels: content 📄, section: start

#157 Update Simulators overview page
  docs/verify/simulators.mdx
Labels: content 📄, section: verify 🧪

#180 combine options topics
  docs/run/_toc.json
  docs/run/advanced-runtime-options.mdx
  docs/run/algorithm-tuning-options.mdx
  docs/run/primitive-options.mdx
  docs/run/primitives-examples.mdx
  docs/start/migrate-examples.mdx
  docs/start/migrate.mdx
Labels: content 📄

#184 Combine how-tos in to a single "simulate with qiskit reference primitives" page
  docs/run/primitives.mdx
  docs/verify/__use_estimator.mdx
  docs/verify/__use_sampler.mdx
  docs/verify/_toc.json
  docs/verify/cloud-based-simulators.mdx
  docs/verify/index.mdx
  docs/verify/simulate-with-qiskit-primitives.mdx
  public/images/verify/simulate-with-qiskit-primitives/estimator-initialize.png
  public/images/verify/simulate-with-qiskit-primitives/sampler-initialize.png
Labels: content 📄

#189 Improve URLs to be more specific
  docs/api/migration-guides/qiskit-runtime-examples.mdx
  docs/api/migration-guides/qiskit-runtime.mdx
  docs/build/_toc.json
  docs/build/qasm-feature-table.mdx
  docs/run/_toc.json
  docs/run/advanced-runtime-options.mdx
  docs/run/backends.mdx
  docs/run/configure-error-mitigation.mdx
  docs/run/configure-error-suppression.mdx
  docs/run/estimate-job-run-time.mdx
  docs/run/fair-share-queue.mdx
  docs/run/manage-cost.mdx
  docs/run/monitor-job.mdx
  docs/run/reserve-system-time.mdx
  docs/run/run-jobs-in-session.mdx
  docs/run/sessions.mdx
  docs/run/system-information.mdx
  docs/verify/_toc.json
  docs/verify/index.mdx
  docs/verify/noisy-simulators.mdx
Labels: infra 🏗️

#182 New Get backend information page
  docs/run/__gathering_system_information.ipynb
  docs/run/_toc.json
  docs/run/backend-information.mdx
  docs/run/backends.mdx
  docs/run/get-backend-information.ipynb
  docs/run/processor-types.mdx
  docs/run/system-information.mdx
Labels: content 📄

#188 remove comparison file
  docs/api/migration-guides/_toc.json
  docs/api/migration-guides/index.mdx
  docs/api/migration-guides/qiskit-runtime-comparison.mdx
  docs/api/migration-guides/qiskit-runtime.mdx
Labels: content 📄

#192 consistency with backend vs system (and fix some links)
  docs/run/get-backend-information.ipynb
  docs/run/system-information.mdx
Labels: content 📄

#201 Remove broken links on Start page
  docs/start/hello-world.ipynb
  docs/start/index.mdx
Labels: content 📄

#212 Fix permalinks with API generation for Sphinx 7.2+
  scripts/lib/sphinx/sphinxHtmlToMarkdown.test.ts
  scripts/lib/sphinx/sphinxHtmlToMarkdown.ts
Labels: infra 🏗️

#76 Autoformat TypeScript with Prettier
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new-content.yaml
  .github/ISSUE_TEMPLATE/ui.yml
  .github/ISSUE_TEMPLATE/user-feedback.yml
  .github/workflows/main.yml
  .prettierignore
  CODE_OF_CONDUCT.md
  README.md
  package-lock.json
  package.json
  scripts/commands/checkLinks.ts
  scripts/commands/declarations.d.ts
  scripts/commands/updateApiDocs.ts
  scripts/lib/GithubApiClient.ts
  scripts/lib/WebCrawler.ts
  scripts/lib/downloadImages.ts
  scripts/lib/fs.ts
  scripts/lib/sphinx/PythonObjectMeta.ts
  scripts/lib/sphinx/SphinxToMdResult.ts
  scripts/lib/sphinx/addFrontMatter.ts
  scripts/lib/sphinx/dedupeIds.test.ts
  scripts/lib/sphinx/dedupeIds.ts
  scripts/lib/sphinx/flatFolders.ts
  scripts/lib/sphinx/generateToc.test.ts
  scripts/lib/sphinx/generateToc.ts
  scripts/lib/sphinx/mergeClassMembers.test.ts
  scripts/lib/sphinx/mergeClassMembers.ts
  scripts/lib/sphinx/sphinxHtmlToMarkdown.test.ts
  scripts/lib/sphinx/sphinxHtmlToMarkdown.ts
  scripts/lib/sphinx/updateLinks.test.ts
  scripts/lib/sphinx/updateLinks.ts
  scripts/lib/stringUtils.ts
  scripts/lib/zx.ts
  tsconfig.json
Labels: infra 🏗️

#242 Delete qasm-circuits.mdx
  docs/build/qasm-circuits.mdx
Labels: content 📄, bug 🐛

#248 Update hello-world.ipynb
  docs/start/hello-world.ipynb
Labels: content 📄

#251 Configure error suppression updates
  docs/run/_toc.json
  docs/run/advanced-runtime-options.mdx
  docs/run/configure-error-suppression.mdx
  docs/run/configure-runtime-compilation.mdx
Labels: content 📄

#75 Clarify how to minimize time
  docs/run/_toc.json
  docs/run/manage-cost.mdx
  docs/run/minimize-time.mdx
Labels: in-progress

#83 Allow a user to define a default account: RELEASE 12.3
  docs/run/account-management.mdx
  docs/start/install.mdx
Labels: on hold ⏸️
