Repository Qiskit/documentation, pull requests merged in 2024-10, with the labels that each got.

#1964 revamp support page
  docs/faq.mdx
  docs/open-source/index.mdx
  docs/support.mdx
  scripts/pr-previews/builder.py
Labels: content 📄

#2064 Add clarifications to execution modes docs
  docs/guides/execution-modes.mdx
  docs/guides/run-jobs-session.mdx
Labels: content 📄

#2090 fix broken (R) symbol
  docs/guides/intro-to-patterns.mdx
Labels: content 📄

#2091 update bug issue template
  .github/ISSUE_TEMPLATE/bug.yaml
Labels: content 📄

#2096 Fix typo in dynamical-decoupling file
  docs/guides/dynamical-decoupling-pass-manager.ipynb
Labels: content 📄, bug 🐛

#2092 add section: How Estimator calculates error
  docs/guides/primitive-input-output.ipynb
Labels: content 📄

#2099 Add latest blog to latest updates page
  docs/guides/latest-updates.mdx
  scripts/js/commands/checkInternalLinks.ts
Labels: content 📄

#2147 Fix external link checker exception handling
  scripts/js/lib/links/ExternalLink.test.ts
  scripts/js/lib/links/ExternalLink.ts
Labels: infra 🏗️

#2165 What's new in the docs updates since early Sept
  docs/guides/_toc.json
  docs/guides/latest-updates.mdx
Labels: content 📄

#2171 make paths safer (tweak to latest updates pg)
  docs/guides/latest-updates.mdx
Labels: content 📄, bug 🐛

#2192 Mention mthree on configure-error-mitigation
  docs/guides/configure-error-mitigation.mdx
Labels: content 📄

#2200 Update examples in get-started-with-primitives
  docs/guides/get-started-with-primitives.ipynb
  docs/guides/get-started-with-primitives.mdx
  scripts/config/notebook-testing.toml
Labels: content 📄
