Repository Qiskit/documentation, pull requests merged in 2024-01, with the labels that each got.

#569 Check Runtime historical API docs for broken links
  .github/workflows/external-link-checker.yml
  .github/workflows/main.yml
  README.md
  scripts/commands/checkLinks.ts
Labels: infra 🏗️, API docs

#585 Minor typo cleanup in transpile section
  docs/transpile/custom-transpiler-pass.ipynb
  docs/transpile/qiskit-transpiler-service.mdx
Labels: content 📄, bug 🐛

#586 Add citation information for composer
  docs/support.mdx
Labels: content 📄

#581 Add more tests for API generation script
  docs/api/qiskit-ibm-provider/index.md
  docs/api/qiskit-ibm-runtime/0.14/index.md
  docs/api/qiskit-ibm-runtime/0.15/index.md
  docs/api/qiskit-ibm-runtime/0.16/index.md
  docs/api/qiskit-ibm-runtime/index.md
  docs/api/qiskit/release-notes/0.45.md
  scripts/commands/updateApiDocs.ts
  scripts/lib/downloadCIArtifacts.test.ts
  scripts/lib/downloadCIArtifacts.ts
  scripts/lib/fs.test.ts
  scripts/lib/sphinx/addFrontMatter.test.ts
  scripts/lib/sphinx/addFrontMatter.ts
  scripts/lib/sphinx/commonParserConfig.ts
  scripts/lib/sphinx/dedupeHtmlIds.test.ts
  scripts/lib/sphinx/dedupeHtmlIds.ts
  scripts/lib/sphinx/flattenFolders.test.ts
  scripts/lib/sphinx/flattenFolders.ts
  scripts/lib/sphinx/mergeClassMembers.ts
  scripts/lib/sphinx/specialCaseResults.test.ts
  scripts/lib/sphinx/specialCaseResults.ts
  scripts/lib/sphinx/sphinxHtmlToMarkdown.ts
  scripts/lib/sphinx/updateLinks.ts
  scripts/lib/stringUtils.test.ts
Labels: infra 🏗️

#592 Run extended checks on API updates
  .github/workflows/extended-checks.yml
Labels: infra 🏗️

#620 Add source links when using `sphinx.ext.viewcode`
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.Estimator.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.IBMBackend.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.ParameterNamespace.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.QiskitRuntimeService.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.RuntimeDecoder.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.RuntimeEncoder.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.RuntimeJob.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.RuntimeOptions.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.RuntimeProgram.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.Sampler.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.Session.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.options.EnvironmentOptions.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.options.ExecutionOptions.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.options.Options.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.options.ResilienceOptions.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.options.SimulatorOptions.md
  docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.options.TranspilationOptions.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.Estimator.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.IBMBackend.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.ParameterNamespace.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.QiskitRuntimeService.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.RuntimeDecoder.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.RuntimeEncoder.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.RuntimeJob.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.RuntimeOptions.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.RuntimeProgram.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.Sampler.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.Session.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.options.EnvironmentOptions.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.options.ExecutionOptions.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.options.Options.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.options.ResilienceOptions.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.options.SimulatorOptions.md
  docs/api/qiskit-ibm-runtime/0.15/qiskit_ibm_runtime.options.TranspilationOptions.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.Estimator.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.IBMBackend.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.QiskitRuntimeService.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.RuntimeDecoder.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.RuntimeEncoder.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.RuntimeJob.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.RuntimeOptions.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.Sampler.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.Session.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.EnvironmentOptions.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.ExecutionOptions.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.Options.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.ResilienceOptions.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.SimulatorOptions.md
  docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.TranspilationOptions.md
  scripts/commands/updateApiDocs.ts
  scripts/lib/api/htmlToMd.test.ts
  scripts/lib/api/htmlToMd.ts
  scripts/lib/api/processHtml.test.ts
  scripts/lib/api/processHtml.ts
Labels: infra 🏗️

#589 Add anchors to show/hide sections in install page
  docs/start/install.mdx
Labels: content 📄, needs discussion 💬, content request

#722 Restore missing content from install page show/hide section
  docs/start/install.mdx
Labels: content 📄, bug 🐛

#487 New Native Gates page
  docs/run/_toc.json
  docs/run/native-gates.mdx
  docs/run/processor-types.mdx
Labels: content 📄, new ✨

#674 Address image issues and associated text in Transpiler stages page
  docs/transpile/transpiler-stages.ipynb
  public/images/transpile/transpiler-stages/layout-mapping.png
  public/images/transpile/transpiler-stages/layout-mapping@dark.png
Labels: content 📄

#731 Tweaks to intro to primitives page
  docs/run/primitives.mdx
Labels: content 📄
