Repository Qiskit/documentation, pull requests merged in 2024-07, with the labels that each got.

#1648 Add r2 to Heron entry in processor-types file
  docs/guides/processor-types.mdx
Labels: content 📄

#1688 Fix typo in Runtime save_account code
  docs/api/migration-guides/qiskit-runtime-from-ibm-provider.mdx
  docs/api/migration-guides/qiskit-runtime-from-ibmq-provider.mdx
Labels: content 📄, bug 🐛

#1689 Typos - minor cleanup
  docs/guides/index.mdx
  docs/guides/intro-to-patterns.mdx
  docs/guides/primitives.mdx
  docs/guides/processor-types.mdx
Labels: content 📄, bug 🐛

#1671 Set up skeleton for Additional Resources dropdown
  cspell/cSpell.json
  cspell/dictionaries/qiskit.txt
  docs/open-source/_toc.json
  docs/open-source/code-of-conduct.mdx
  docs/open-source/index.mdx
  docs/open-source/qiskit-sdk-version-strategy.mdx
  docs/responsible-quantum-computing.mdx
  scripts/lib/links/ignores.ts
Labels: infra 🏗️
