Repository Qiskit/documentation, pull requests merged in 2025-07, with the labels that each got.

#3475 Search for quantum.ibm.com in docs repo
  CODE_OF_CONDUCT.md
  docs/faq.mdx
  docs/guides/DAG-representation.ipynb
  docs/guides/algorithmiq-tem.ipynb
  docs/guides/common-parameters.ipynb
  docs/guides/fair-share-scheduler.mdx
  docs/guides/function-template-hamiltonian-simulation.ipynb
  docs/guides/functions.ipynb
  docs/guides/get-qpu-information.ipynb
  docs/guides/ibm-circuit-function.ipynb
  docs/guides/index.mdx
  docs/guides/install-qiskit.mdx
  docs/guides/kipu-optimization.ipynb
  docs/guides/max-execution-time.ipynb
  docs/guides/monitor-job.ipynb
  docs/guides/multiverse-computing-singularity.ipynb
  docs/guides/native-gates.ipynb
  docs/guides/primitives-rest-api.ipynb
  docs/guides/processor-types.mdx
  docs/guides/pulse.ipynb
  docs/guides/q-ctrl-optimization-solver.ipynb
  docs/guides/q-ctrl-performance-management.ipynb
  docs/guides/qedma-qesem.ipynb
  docs/guides/qiskit-code-assistant-vscode.mdx
  docs/guides/qpu-information.mdx
  docs/guides/qunova-chemistry.ipynb
  docs/guides/save-jobs.ipynb
  docs/guides/serverless-first-program.ipynb
  docs/guides/serverless-run-first-workload.ipynb
  docs/migration-guides/classic-iqp-to-cloud-iqp.mdx
  docs/migration-guides/migrate-classic-rest-api.mdx
  docs/tutorials/error-mitigation-with-qiskit-functions.ipynb
  docs/tutorials/qunova-hivqe.ipynb
  docs/tutorials/solve-higher-order-binary-optimization-problems-with-q-ctrls-optimization-solver.ipynb
Labels: content 📄

#3542 Update qiskit_bot.yaml to add tutorials owners
  qiskit_bot.yaml
Labels: tutorial 📒, needs triage 🤔

#3493 Update long range entanglement tutorial
  docs/tutorials/long-range-entanglement.ipynb
  public/docs/images/tutorials/long-range-entanglement-with-limited-qubit-connectivity/paper-plot.avif
  public/docs/images/tutorials/long-range-entanglement-with-limited-qubit-connectivity/post-processing-illustration.avif
  public/docs/images/tutorials/long-range-entanglement-with-limited-qubit-connectivity/sherbrooke-1d-line.avif
  public/docs/images/tutorials/long-range-entanglement/extracted-outputs/03ab7ed7-0.avif
  public/docs/images/tutorials/long-range-entanglement/extracted-outputs/0400e350-0.avif
  public/docs/images/tutorials/long-range-entanglement/extracted-outputs/db53b428-14e0-485a-9e9e-b17d59936c02-0.avif
  public/docs/images/tutorials/long-range-entanglement/extracted-outputs/e048983d-0441-40a1-944f-6f6725f01096-0.avif
  public/docs/images/tutorials/long-range-entanglement/extracted-outputs/f80209e2-0.avif
  public/docs/images/tutorials/long-range-entanglement/extracted-outputs/f9277469-cc4e-464c-b803-e11f6ad3603a-0.avif
Labels: tutorial 📒
