Repository Qiskit/documentation, pull requests merged in 2025-05, with the labels that each got.

#3069 Minor fixes to the timing pages
  docs/guides/max-execution-time.mdx
  docs/guides/minimize-time.mdx
  docs/guides/noise-learning.ipynb
Labels: content 📄

#3103 Update c-extension-for-python.mdx
  docs/guides/c-extension-for-python.mdx
Labels: content 📄

#3104 Remove duplicate step 1 in Grovers tutorial
  docs/tutorials/grovers-algorithm.ipynb
Labels: content 📄

#3092 Local estimation (before submitting job)
  docs/guides/_toc.json
  docs/guides/estimate-job-run-time.mdx
Labels: content 📄

#3102 New Platform updates for Latest Updates pg
  docs/guides/latest-updates.mdx
Labels: content 📄

#3113 Specify rolling plan is for Premium only
  docs/guides/fair-share-scheduler.mdx
Labels: content 📄

#3120 Update tutorial category name
  docs/tutorials/_toc.json
  docs/tutorials/index.mdx
Labels: tutorial 📒

#3121 add latest releases of Qiskit, Runtime, Serverless, and Functions to Latest updates page
  docs/guides/latest-updates.mdx
  scripts/js/commands/checkInternalLinks.ts
Labels: content 📄

#3115 Fix small error
  docs/guides/hello-world.ipynb
Labels: content 📄, needs triage 🤔
